apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  CLUSTER_ID: "3z9xN1AMRW2ZWmMU5f-xEQ" # docker-compose에서 사용했던 ID
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_NODE_ID: "1"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
  KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-service:9092" # K8s 내부 통신용
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"