replicaCount: 1
image:
  repository: ldhbenecia/msa-playground-user-service
  tag: "8ea93d5" # 이미지 버전
  pullPolicy: IfNotPresent # 이미지가 로컬에 존재하면 pull 안함
service:
  name: user-service
  port: 8081
  targetPort: 8081
configMap:
  name: user-service-config
  data:
    DB_URL: "jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1"
    KAFKA_BROKERS: "kafka-service:9092"
secret:
  name: user-service-secret
  data:
    DB_USER: "sa"
    DB_PASSWORD: ""
rbac:
  serviceAccountName: msa-service-account
