replicaCount: 1

image:
  repository: ldhbenecia/msa-playground-user-service
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  name: api-gateway-service
  port: 80
  targetPort: 8000
  type: LoadBalancer

configMap:
  name: api-gateway-service
  data:
    SERVER_PORT: 8000
    # K8s Service Discovery 활성화 (최신 키)
    GATEWAY_DISCOVERY_ENABLED: "true"
    GATEWAY_DISCOVERY_LOWERCASE: "true"

rbac:
  serviceAccountName: msa-service-account
